**Actividad 2.1 (Extracción de datos)**
**Eduardo Ballinas Ballinas**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Lectura de los datos**

In [2]:
dp=pd.read_excel("Detalle precios y productos fabricados 2022.xlsx")
dp

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**1. Filtro por objeto**

In [3]:
objeto=dp[(dp["NOMBRE_CLIENTE"] == "VINILOS")]
objeto

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
80,F37180,2022-01-24,ALFREDO CANELA,VINILOS,10,TP0004,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2.5 MT,272.0,77.13,77.13,2720.0,771.29,194.87,1948.71
505,F37980,2022-04-26,ALFREDO CANELA,VINILOS,10,TP0003,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2 MT,250.0,72.37,72.37,2500.0,723.67,177.63,1776.33
984,F38967,2022-09-02,ALFREDO CANELA,VINILOS,10,TP0004,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2.5 MT,386.0,84.41,84.41,3860.0,844.11,301.59,3015.89
1019,F39029,2022-09-12,AARON NUÑO CORDOVA,VINILOS,10,TP0004,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 2.5 MT,386.0,77.13,77.13,3860.0,771.29,308.87,3088.71

**2. Filtro por filas**

In [4]:
filas=dp.iloc[2:6,:]
filas

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32

**3. Filtro por columnas**

In [5]:
columnas=dp.iloc[:,0:4]
columnas

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL
...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS

**4. Filtro de filas por columnas**

In [6]:
dp1=pd.read_excel("Detalle precios y productos fabricados 2022.xlsx",index_col="CANT")
dp1=dp1.loc[[1,2],["NOMBRE_CLIENTE", "PRECIO_UNITARIO", "COSTO_UNITARIO"]]
dp1

                           NOMBRE_CLIENTE  PRECIO_UNITARIO  COSTO_UNITARIO
CANT
1                      PÚBLICO EN GENERAL           434.48           52.80
1            JUAN ANTONIO RESENDIZ UGALDE          1264.05          327.18
1                    OMAR RODRIGUEZ GOMEZ           140.00           38.96
1     AIRBUS HELICOPTERS MEXICO QUERETARO         14000.00         5323.76
1                      FIDEICOMISO F/1596          1615.00          517.89
...                                   ...              ...             ...
2                      PÚBLICO EN GENERAL           732.00            0.00
2                         TRILOGIQ-MEXICO           925.82           65.31
2                         TRILOGIQ-MEXICO          1910.50          286.13
2                         TRILOGIQ-MEXICO          2020.42          421.91
2                         TRILOGIQ-MEXICO          1177.07          477.16

[831 rows x 3 columns]

**5. Filtro por cabecera**

In [7]:
cabecera=dp.head(10)
cabecera

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
5,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00243,BAN P INOX 55MMX235MM 450W 127V T/TOR,237.07,49.41,49.41,474.14,98.82,187.66,375.32
6,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24
7,F37046,2022-01-05,LETICIA RAMIREZ HERNANDEZ,ANA BARBARA CRUZ PALACIOS,3,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,94.50,38.96,38.96,283.50,116.88,55.54,166.62
8,F37048,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11
9,F37049,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,517.89,517.89,1615.00,517.89,1097.11,1097.11

**6. Filtro por cola**

In [8]:
cola=dp.tail(10)
cola

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1416,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
1417,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BL00002,BL INOX 60mmØx50mm 400W 120/240V EXT30CM,925.82,65.31,65.31,1851.64,130.63,860.51,1721.01
1418,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00145,BAN INOX 146MMØX40MM 500W230V CINT/ALLEN,1910.50,286.13,286.13,3821.00,572.25,1624.37,3248.75
1419,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00146,"BAN INOX 9""ØX3"" ANCH 1700W 230V T/CABLE",2020.42,421.91,421.91,4040.84,843.82,1598.51,3197.02
1420,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,PT00079,PT-100 7.5MMØX95MM EXT.48CM 3H C/MACHO,1177.07,477.16,477.16,2354.14,954.32,699.91,1399.82
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

**7. Filtro por comparación**

In [ ]:
comparacion=dp[dp["PRECIO_UNITARIO"]>20000]
comparacion

**8. Filtro Y (Conjunción)**

In [ ]:
conjuncion=dp[(dp["NOMBRE_VENDEDOR"]=="LETICIA RAMIREZ HERNANDEZ") & (dp["NOMBRE_CLIENTE"]=="PÚBLICO EN GENERAL") & (dp["SUBTOTAL_PARTIDA"]>4000)]
conjuncion

**9. Filtro O (Disyunción)**

In [ ]:
disyuncion=dp[(dp["CANT"]>15) | (dp["PRECIO_UNITARIO"]>10000)]
disyuncion

**10. Filtro Not (Negación)**

In [ ]:
negacion=dp[~(dp["COSTO_UNITARIO"]==0)]
negacion